package org.trustify.operator.services;

import io.fabric8.kubernetes.api.model.Secret;
import org.trustify.operator.Constants;
import org.trustify.operator.TrustifyConfig;
import org.trustify.operator.cdrs.v2alpha1.Trustify;

import java.util.Optional;

public interface Cluster {
    Optional<String> getAutoGeneratedIngressHost(Trustify cr);

    Optional<Secret> getAutoGeneratedServerTlsSecret(Trustify cr);

    TrustifyConfig.KeycloakSubscriptionConfig getKeycloakSubscriptionConfig();

    static String getServerSelfGeneratedTlsSecretName(Trustify cr) {
        return cr.getMetadata().getName() + "-" + Constants.TRUSTI_SERVER_NAME + "-tls";
    }
}
