apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: trustify-catalog-source
  namespace: olm
spec:
  sourceType: grpc
  image: ghcr.io/trustification/trustify-operator-bundle:latest
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: mynamespace
spec:
  targetNamespaces:
    - mynamespace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trustify-subscription
  namespace: mynamespace
spec:
  channel: alpha
  name: trustify-operator
  source: trustify-catalog-source
  sourceNamespace: olm
