name: Make Operator Bundle
description: |
  Make an operator bundle. This does not save the image for you.
inputs:
  operator_bundle:
    description: "image uri for operator bundle (ie. ghcr.io/<namespace>/<image-name>:<tag>)"
    required: true
  operator:
    description: "image uri for operator (ie. ghcr.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  ui:
    description: "image uri for trustify-ui server (ie. ghcr.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  server:
    description: "image uri for trustify server (ie. ghcr.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  server_postgres:
    description: "image uri for trustify postgres (ie. ghcr.io/<namespace>/<image-name>:<tag>)"
    required: false
    default: ""
  version:
    description: "operator version"
    required: false
    default: ""
  channels:
    description: "comma separated channel(s) this operator should be available on"
    required: false
    default: ""
  push_bundle:
    description: ""
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
  - name: Make and Push bundle
    env:
      BUNDLE_IMG: ${{ inputs.operator_bundle }}
    run: |
      [ -n "${{ inputs.channels }}" ] && export CHANNELS="${{ inputs.channels }}"
      [ -n "${{ inputs.version }}" ] && export VERSION="${{ inputs.version }}"
      [ -n "${VERSION}" ] && export VERSION="${VERSION:1}"
      [ -n "${{ inputs.operator }}" ] && export IMG="${{ inputs.operator }}"

      OPTS=""
      [ -n "${{ inputs.ui }}" ] && OPTS+=" -Drelated.image.ui=${{ inputs.ui }}"
      [ -n "${{ inputs.server }}" ] && OPTS+=" -Drelated.image.server=${{ inputs.server }}"
      [ -n "${{ inputs.server_postgres }}" ] && OPTS+=" -Drelated.image.db=${{ inputs.server_postgres }}"

      QUARKUS_OPTS="${OPTS}" make bundle-build
      docker cp $(docker create --name download $BUNDLE_IMG ls):/manifests/trustify-operator.clusterserviceversion.yaml . && docker rm download
      cat trustify-operator.clusterserviceversion.yaml
    working-directory: ${{ github.action_path }}/../../..
    shell: bash

  - name: Push bundle
    if: ${{ inputs.push_bundle == 'true' }}
    env:
      BUNDLE_IMG: ${{ inputs.operator_bundle }}
    run: |
      make bundle-push
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
